name: .NET Core

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5.11.0
      with:
        name: 1.3.0
        tag: 1.3.0
