name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: release-drafter/release-drafter@v5
      with:
          template:
            $CHANGES
          name: 1.5.0
          tag: 1.5.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
